import java.util.Properties

plugins {
    id("com.android.application")
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")
}

val keystoreProperties = Properties()
val keystorePropertiesFile = rootProject.file("key.properties")
if (keystorePropertiesFile.exists()) {
    keystorePropertiesFile.inputStream().use(keystoreProperties::load)
}

// Production mapping is generated by flutterfire after the owner chooses the
// final application ID. Emulator/guest builds intentionally need no file.
if (file("google-services.json").exists()) {
    apply(plugin = "com.google.gms.google-services")
}

android {
    buildFeatures {
        buildConfig = true
    }

    namespace = "com.tungbogin.cudoi"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    defaultConfig {
        applicationId = "com.tungbogin.cudoi"
        // You can update the following values to match your application needs.
        // For more information, see: https://flutter.dev/to/review-gradle-config.
        minSdk = flutter.minSdkVersion
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName
        buildConfigField("boolean", "LEADERBOARDS_ENABLED", "false")
    }


    signingConfigs {
        create("release") {
            check(keystorePropertiesFile.exists()) {
                "Missing android/key.properties required for release signing"
            }
            keyAlias = keystoreProperties["keyAlias"] as String
            keyPassword = keystoreProperties["keyPassword"] as String
            storeFile = file(keystoreProperties["storeFile"] as String)
            storePassword = keystoreProperties["storePassword"] as String
        }
    }

    buildTypes {
        release {
            signingConfig = signingConfigs.getByName("release")
        }
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}

flutter {
    source = "../.."
}

dependencies {
    implementation("com.google.android.gms:play-services-games-v2:22.0.0")
    // Google Mobile Ads 25.4.0 still requests WorkManager 2.7.0. Its Room
    // runtime predates the consumer R8 rule that preserves the generated
    // WorkDatabase constructor, so minified release builds crash in
    // InitializationProvider before Flutter starts. Keep WorkManager current
    // explicitly until the ads SDK raises its transitive dependency.
    implementation("androidx.work:work-runtime:2.11.2")
    testImplementation("junit:junit:4.13.2")
}

// The Play Console owns these values. Keep development placeholders explicit,
// but make it impossible to accidentally ship them in a release artifact.
val validatePlayGamesReleaseConfiguration =
    tasks.register("validatePlayGamesReleaseConfiguration") {
        val catalogFile = layout.projectDirectory.file("src/main/res/values/leaderboards.xml")
        inputs.file(catalogFile)

        doLast {
            if (!android.defaultConfig.buildConfigFields["LEADERBOARDS_ENABLED"]
                    .toString().contains("true")) return@doLast
            val source = catalogFile.asFile.readText()
            fun stringResource(name: String): String {
                val match = Regex(
                    """<string\s+[^>]*name=["']${Regex.escape(name)}["'][^>]*>(.*?)</string>""",
                    setOf(RegexOption.IGNORE_CASE, RegexOption.DOT_MATCHES_ALL),
                ).find(source)
                return match?.groupValues?.get(1)?.trim()
                    ?: throw GradleException("Missing Play Games resource: $name")
            }

            fun requireProductionValue(name: String, value: String) {
                val normalized = value.lowercase()
                val placeholder =
                    value.isBlank() ||
                        listOf("replace_with", "placeholder", "todo", "changeme").any {
                            normalized.contains(it)
                        }
                if (placeholder) {
                    throw GradleException(
                        "Play Games release configuration contains a placeholder: $name",
                    )
                }
            }

            val projectId = stringResource("game_services_project_id")
            requireProductionValue("game_services_project_id", projectId)
            if (!projectId.matches(Regex("[0-9]{6,}"))) {
                throw GradleException("game_services_project_id must be the numeric Play Games project ID")
            }

            val configuredApplicationId = stringResource("play_games_android_application_id")
            requireProductionValue("play_games_android_application_id", configuredApplicationId)
            val releaseApplicationId = android.defaultConfig.applicationId
            if (configuredApplicationId != releaseApplicationId) {
                throw GradleException(
                    "Play Games application ID does not match Android applicationId",
                )
            }

            val leaderboardIds = (1..20).map { arenaId ->
                val name = "leaderboard_arena_$arenaId"
                stringResource(name).also { requireProductionValue(name, it) }
            }
            if (leaderboardIds.toSet().size != 20) {
                throw GradleException("Play Games requires 20 unique leaderboard IDs")
            }
        }
    }

tasks.matching { it.name == "preReleaseBuild" }.configureEach {
    dependsOn(validatePlayGamesReleaseConfiguration)
}
